PROJECT=/home/tzhou/explore/numa/
all: show array-access conflict

show:
	make -f $(PROJECT)src/$@/makefile

array-access:
	make -f $(PROJECT)src/$@/makefile

conflict:
	make -f $(PROJECT)src/$@/makefile
