PROJECT=/home/tzhou/explore/numa/
all: show array-access conflict move-pages

show:
	make -f $(PROJECT)src/$@/makefile

array-access:
	make -f $(PROJECT)src/$@/makefile

conflict:
	make -f $(PROJECT)src/$@/makefile

move-pages:
	make -f $(PROJECT)src/$@/makefile DNAME=$@

